 DECLARE EmployeeData CURSOR FOR SELECT EMPLOYEE_ID , FIRST_NAME,LAST_NAME,SALARY FROM RCJNFRJR_EMPLOYEE
 
 OPEN EmployeeData
 
    --siguiente fila
    FETCH NEXT FROM EmployeeData INTO @EMPLOYEE_ID, @FIRST_NAME, @LAST_NAME, @SALARY

    --mientras haya filas
    WHILE @@FETCH_STATUS = 0
    BEGIN

        --HACER UN SELET, IF ETC, OPERAR LOS DATOS ETC


        ----------------

        FETCH NEXT FROM EmployeeData INTO @EMPLOYEE_ID, @FIRST_NAME, @LAST_NAME, @SALARY
    END
 
 CLOSE EmployeeData
 
 DEALLOCATE EmployeeData








 ----------------------------- CURSOR --------------------------------

--CURSOR PARA LISTAR EMPLEADOS Y SUS TRABAJOS
CREATE OR REPLACE PROCEDURE LIST_EMPLOYEE_JOBS IS
    CURSOR EMPLOYEE_CURSOR IS
        SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE
        FROM RCJNFRJR_EMPLOYEE E
        JOIN RCJNFRJR_JOBS J ON E.JOB_ID = J.JOB_ID;
BEGIN
    FOR EMPLOYEE_RECORD IN EMPLOYEE_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLOYEE_RECORD.FIRST_NAME ||' '|| EMPLOYEE_RECORD.LAST_NAME ||' '|| EMPLOYEE_RECORD.JOB_TITLE);
    END LOOP;
END;