create or replace NONEDITIONABLE PROCEDURE RCJNFRJR_INSERT_EMPLOYEE(
    FIRST_NAME_P VARCHAR2 DEFAULT NULL,
    LAST_NAME_P VARCHAR2 DEFAULT NULL,
    SALARY_P NUMBER,
    HIRE_DATE_P DATE,
    JOB_ID_P VARCHAR2,
    BANK_NAME_P VARCHAR2,
    ACCOUNT_TYPE_P VARCHAR2,
    SERV_NAME_P VARCHAR2,
    WORKED_DAYS_P NUMBER,
    ACCOUNT_NUMBER_P NUMBER,
    Asigned_Service_P VARCHAR2
)
IS
    
    --V_EMPLOYEE_ID NUMBER:= SEQ_EMPLOYEE_ID.NEXTVAL;
  
BEGIN
    LOCK TABLE RCJNFRJR_EMPLOYEE, RCJNFRJR_REGISTER, RCJNFRJR_BANK_ACCOUNT, RCJNFRJR_SERVICE, RCJNFRJR_DETAIL_SERVICE_EMPLOYEE IN ROW EXCLUSIVE MODE;

    --Estas tablas deben ser actualizadas a nivel operativo, cuando creamos un empleado no existen valores aun
    --Lo unico que q hay q crear es el registro para ese empleado del inicio de operaciones
    INSERT INTO RCJNFRJR_REGISTER(REGISTER_DATE,REGISTER_STATE)
        VALUES(SYSDATE, 'Inicio de operaciones');

    INSERT INTO RCJNFRJR_BANK_ACCOUNT(ACCOUNT_NUMBER, BANK_NAME, ACCOUNT_TYPE)
        VALUES(ACCOUNT_NUMBER_P, BANK_NAME_P, ACCOUNT_TYPE_P);

    INSERT INTO RCJNFRJR_EMPLOYEE(FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE, ID_REGISTER, ACCOUNT_NUMBER, JOB_ID)
        VALUES(FIRST_NAME_P, LAST_NAME_P, SALARY_P, HIRE_DATE_P, V_ID_REGISTER, ACCOUNT_NUMBER_p, JOB_ID_P);

    -- SELECT ID_SERVICE INTO V_ID_SERVICE
    -- FROM RCJNFRJR_SERVICE
    -- WHERE SERV_NAME = SERV_NAME_P;

    --Servicio deberia ser una tabla que se actuializa tmbn, debe existir una funcion o procedimiento que actualice un servicio y asigne un empleado
    -- INSERT INTO RCJNFRJR_DETAIL_SERVICE_EMPLOYEE(EMPLOYEE_ID, ID_SERVICE, WORKED_DAYS)
    --     VALUES(WORKED_DAYS_P);

    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Servicio no encontrado.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010, 'Ocurrió un error inesperado.');
    ROLLBACK;
END;