create or replace NONEDITIONABLE PROCEDURE RCJNFRJR_INSERT_EMPLOYEE(
    FIRST_NAME_P VARCHAR2 DEFAULT NULL,
    LAST_NAME_P VARCHAR2 DEFAULT NULL,
    SALARY_P NUMBER,
    HIRE_DATE_P DATE,
    BANK_NAME_P VARCHAR2,
    ACCOUNT_TYPE_P VARCHAR2,
    ACCOUNT_NUMBER_P NUMBER,
    JOB_ID_P VARCHAR2
    
)
IS
    
   

BEGIN
    LOCK TABLE RCJNFRJR_EMPLOYEE,RCJNFRJR_BANK_ACCOUNT IN ROW EXCLUSIVE MODE;



    INSERT INTO RCJNFRJR_BANK_ACCOUNT(ACCOUNT_NUMBER, BANK_NAME, ACCOUNT_TYPE)
        VALUES(ACCOUNT_NUMBER_P, BANK_NAME_P, ACCOUNT_TYPE_P);

    INSERT INTO RCJNFRJR_EMPLOYEE(EMPLOYEE_ID,FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE, ACCOUNT_NUMBER,JOB_ID)
        VALUES(NULL,FIRST_NAME_P, LAST_NAME_P, SALARY_P, HIRE_DATE_P, ACCOUNT_NUMBER_p,NULL);



    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Datos no encontrados.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM); -- Registrar error
        RAISE_APPLICATION_ERROR(-20010, 'Ocurrió un error inesperado: ' || SQLERRM);
        ROLLBACK;
END;


INSERT INTO RCJNFRJR_BANK_ACCOUNT(ACCOUNT_NUMBER, BANK_NAME, ACCOUNT_TYPE)
    VALUES(12345, 'BANCOESTADO', 'CORRIENTE');

INSERT INTO RCJNFRJR_EMPLOYEE(EMPLOYEE_ID,FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE, ACCOUNT_NUMBER,JOB_ID)
    VALUES(NULL,'Juan1', 'Soto', 500000, SYSDATE, 12345,NULL);




BEGIN
   RCJNFRJR_INSERT_EMPLOYEE(
      'juan1',        -- first_name
      'soto',         -- last_name
      570000,         -- salary (sin punto como separador decimal, si es un número entero)
      SYSDATE,
      'BANCO ESTADO',
      'CUENTA CORRIENTE',
      1234567
   );
END;