-- CREATE BY: RODRIGO CARTER, JOAQUIN NOVAS, FABIOLA RAMÍREZ, JOAQUIN REYES

-------------------------- DROP TABLES ----------------------------

DROP TABLE RCJNFRJR_DETAIL_SERVICE_EQUIPMENT;
DROP TABLE RCJNFRJR_EQUIPMENT;
DROP TABLE RCJNFRJR_DETAIL_SERVICE_MATERIALS;
DROP TABLE RCJNFRJR_MATERIALS;
DROP TABLE RCJNFRJR_INVENTORY;
DROP TABLE RCJNFRJR_LOCATIONS;
DROP TABLE RCJNFRJR_COUNTRIES;
DROP TABLE RCJNFRJR_REGIONS;
DROP TABLE RCJNFRJR_DETAIL_SERVICE_EMPLOYEE;
DROP TABLE RCJNFRJR_EMPLOYEE;
DROP TABLE RCJNFRJR_SERVICE;
DROP TABLE RCJNFRJR_BANK_ACCOUNT;
DROP TABLE RCJNFRJR_JOBS;
DROP TABLE RCJNFRJR_REGISTER;
DROP TABLE RCJNFRJR_LOG;

-------------------------- CREATE TABLES --------------------------

CREATE TABLE RCJNFRJR_LOG_in(
    ID_LOGIN NUMBER,
    USERNAME VARCHAR2(50),
    PASS_LOGIN NUMBER,

    CONSTRAINT PK_RCJNFRJR_LOG PRIMARY KEY(ID_LOGIN)
);



CREATE TABLE RCJNFRJR_REGISTER(
    ID_REGISTER NUMBER,
    REGISTER_DATE DATE, --fecha de creacon del registro
    REGISTER_STATE VARCHAR2(30), --por ejemplo: inicio de operaciones(para cundo se crea un empleado),activo, inactivo, suspendido, etc.
    REGISTER_START_DATE DATE, --fecha de horas de entrada del empleado
    REGISTER_END_DATE DATE, --fecha de horas de salida del empleado
    

    CONSTRAINT PK_RCJNFRJR_REGISTER PRIMARY KEY(ID_REGISTER)


    CONSTRAINT FK_RCJNFRJR_REGISTER_EMPLOYEE
    FOREIGN KEY(EMPLOYEE_ID)
    REFERENCES RCJNFRJR_EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE RCJNFRJR_JOBS(
    JOB_ID VARCHAR2(10),
    JOB_TITLE VARCHAR2(40),

    CONSTRAINT PK_RCJNFRJR_JOB PRIMARY KEY(JOB_ID)
);

CREATE TABLE RCJNFRJR_BANK_ACCOUNT(
    ACCOUNT_NUMBER NUMBER,
    BANK_NAME VARCHAR2(30),
    ACCOUNT_TYPE VARCHAR(10),

    CONSTRAINT PK_RCJNFRJR_BANK_ACCOUNT PRIMARY KEY(ACCOUNT_NUMBER)
);

CREATE TABLE RCJNFRJR_SERVICE(
    ID_SERVICE NUMBER,
    SERV_NAME VARCHAR2(50),
    SERV_DESCRIPTION VARCHAR2(500),
    STARTDATE DATE,
    ENDDATE DATE,
    SERV_CONDITION VARCHAR2(30),
    
    CONSTRAINT PK_RCJNFRJR_SERVICE PRIMARY KEY(ID_SERVICE)
);

CREATE TABLE RCJNFRJR_EMPLOYEE(
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    SALARY NUMBER,
    HIRE_DATE DATE,
    
    ACCOUNT_NUMBER NUMBER,
    JOB_ID VARCHAR2(10),

    CONSTRAINT PK_RCJNFRJR_EMPLOYEE PRIMARY KEY(EMPLOYEE_ID),

    -- CONSTRAINT FK_RCJNFRJR_EMPLOYEE_REGISTER
	--     FOREIGN KEY(ID_REGISTER)
	--     REFERENCES RCJNFRJR_REGISTER(ID_REGISTER),

    CONSTRAINT FK_RCJNFRJR_EMPLOYEE_BANK_ACCOUNT
	    FOREIGN KEY(ACCOUNT_NUMBER)
	    REFERENCES RCJNFRJR_BANK_ACCOUNT(ACCOUNT_NUMBER),

    CONSTRAINT FK_RCJNFRJR_EMPLOYEE_JOBS
	    FOREIGN KEY(JOB_ID)
	    REFERENCES RCJNFRJR_JOBS(JOB_ID)
);

CREATE TABLE RCJNFRJR_DETAIL_SERVICE_EMPLOYEE(
    EMPLOYEE_ID NUMBER,
    ID_SERVICE NUMBER,
    WORKED_DAYS NUMBER,

    CONSTRAINT PK_RCJNFRJR_DETAIL_SERVICE_EMPLOYEE PRIMARY KEY(EMPLOYEE_ID, ID_SERVICE),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_EMPLOYEE_EMPLOYEE
        FOREIGN KEY(EMPLOYEE_ID)
        REFERENCES RCJNFRJR_EMPLOYEE(EMPLOYEE_ID),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_EMPLOYEE_SERVICE
        FOREIGN KEY(ID_SERVICE)
        REFERENCES RCJNFRJR_SERVICE(ID_SERVICE)
);

CREATE TABLE RCJNFRJR_REGIONS(
    REGION_ID NUMBER,
    REGION_NAME VARCHAR2(50),

    CONSTRAINT PK_RCJNFRJR_REGIONS PRIMARY KEY(REGION_ID)
);

CREATE TABLE RCJNFRJR_COUNTRIES(
    COUNTRY_ID NUMBER,
    COUNTRY_NAME VARCHAR2(50),
    REGION_ID NUMBER,

    CONSTRAINT PK_RCJNFRJR_COUNTRIES PRIMARY KEY(COUNTRY_ID),

    CONSTRAINT FK_RCJNFRJR_COUNTRIES_REGIONS
        FOREIGN KEY(REGION_ID)
        REFERENCES RCJNFRJR_REGIONS(REGION_ID)
);

CREATE TABLE RCJNFRJR_LOCATIONS(
    LOCATION_ID NUMBER,
    STREET_ADDRESS VARCHAR2(30),
    ADDRESS_NUMBER NUMBER,
    COUNTRY_ID NUMBER,

    CONSTRAINT PK_RCJNFRJR_LOCATIONS PRIMARY KEY(LOCATION_ID),

    CONSTRAINT FK_RCJNFRJR_LACATIONS_COUNTRIES
        FOREIGN KEY(COUNTRY_ID)
        REFERENCES RCJNFRJR_COUNTRIES(COUNTRY_ID)
);

CREATE TABLE RCJNFRJR_INVENTORY(
    ID_INVENTORY NUMBER,
    LOCATION_ID NUMBER,

    CONSTRAINT PK_RCJNFRJR_INVENTORY PRIMARY KEY(ID_INVENTORY),

    CONSTRAINT FK_RCJNFRJR_INVENTORY_LOCATIONS
        FOREIGN KEY(LOCATION_ID)
        REFERENCES RCJNFRJR_LOCATIONS(LOCATION_ID)
);

CREATE TABLE RCJNFRJR_MATERIALS(
    ID_MATERIALS NUMBER,
    MATERIAL_NAME VARCHAR2(30),
    MATERIAL_QUANTITY NUMBER,
    MATERIAL_MIN_QUANTITY NUMBER,
    ID_INVENTORY NUMBER,

    CONSTRAINT PK_RCJNFRJR_MATERIALS PRIMARY KEY(ID_MATERIALS),

    CONSTRAINT FK_RCJNFRJR_MATERIALS_INVENTORY
        FOREIGN KEY(ID_INVENTORY)
        REFERENCES RCJNFRJR_INVENTORY(ID_INVENTORY)
);

CREATE TABLE RCJNFRJR_DETAIL_SERVICE_MATERIALS(
    ID_MATERIALS NUMBER,
    ID_SERVICE NUMBER,

    CONSTRAINT PK_RCJNFRJR_DETAIL_SERVICE_MATERIALS PRIMARY KEY(ID_MATERIALS, ID_SERVICE),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_MATERIALS_MATERIALS
        FOREIGN KEY(ID_MATERIALS)
        REFERENCES RCJNFRJR_MATERIALS(ID_MATERIALS),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_MATERIALS_SERVICE
        FOREIGN KEY(ID_SERVICE)
        REFERENCES RCJNFRJR_SERVICE(ID_SERVICE)
);

CREATE TABLE RCJNFRJR_EQUIPMENT(
    ID_EQUIPMENT NUMBER,
    EQUIPMENT_NAME VARCHAR2(30),
    EQUIPMENT_QUANTITY NUMBER,
    EQUIPMENT_MIN_QUANTITY NUMBER,
    EQUIPMENT_CONDITION VARCHAR2(30),
    ID_INVENTORY NUMBER,

    CONSTRAINT PK_RCJNFRJR_EQUIPMENT PRIMARY KEY(ID_EQUIPMENT),

    CONSTRAINT FK_RCJNFRJR_EQUIPMENT_INVENTORY
        FOREIGN KEY(ID_INVENTORY)
        REFERENCES RCJNFRJR_INVENTORY(ID_INVENTORY)
);

CREATE TABLE RCJNFRJR_DETAIL_SERVICE_EQUIPMENT(
    ID_EQUIPMENT NUMBER,
    ID_SERVICE NUMBER,

    CONSTRAINT PK_RCJNFRJR_DETAIL_SERVICE_EQUIPMENT PRIMARY KEY(ID_EQUIPMENT, ID_SERVICE),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_EQUIPMENT_EQUIPMENT
        FOREIGN KEY(ID_EQUIPMENT)
        REFERENCES RCJNFRJR_EQUIPMENT(ID_EQUIPMENT),

    CONSTRAINT FK_RCJNFRJR_DETAIL_SERVICE_EQUIPMENT_SERVICE
        FOREIGN KEY(ID_SERVICE)
        REFERENCES RCJNFRJR_SERVICE(ID_SERVICE)
);