----------------------------- TRIGGERS --------------------------------

--HACE QUE LA FECHA DE CONTRATACIÓN SE ACTUALICE CADA VEZ QUE SE INSERTE
--UN NUEVO EMPLEADO
CREATE OR REPLACE TRIGGER RCJNFRJR_UPDATE_HIRE_DATE
AFTER INSERT 
ON RCJNFRJR_EMPLOYEE
FOR EACH ROW
BEGIN
    UPDATE RCJNFRJR_REGISTER
    SET HIRE_DATE = :NEW.HIRE_DATE
    WHERE ID_REGISTER = :NEW.ID_REGISTER;
END;

CREATE OR REPLACE TRIGGER RCJNFRJR_TRG_SERVICE
BEFORE INSERT 
ON RCJNFRJR_SERVICE
FOR EACH ROW
BEGIN
    :NEW.ID_SERVICE := SEQ_SERVICE.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER RCJNFRJR_TRG_INVENTORY
BEFORE INSERT 
ON RCJNFRJR_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.ID_INVENTORY := SEQ_INVENTORY.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER RCJNFRJR_TRG_MATERIALS
BEFORE INSERT 
ON RCJNFRJR_MATERIALS
FOR EACH ROW
BEGIN
    :NEW.ID_MATERIALS := SEQ_MATERIALS.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER RCJNFRJR_TRG_EQUIPMENT
BEFORE INSERT 
ON RCJNFRJR_EQUIPMENT
FOR EACH ROW
BEGIN
    :NEW.ID_EQUIPMENT := SEQ_EQUIPMENT.NEXTVAL;
END;



CREATE OR REPLACE TRIGGER RCJNFRJR_PK_EMPLOYEE
BEFORE INSERT
ON RCJNFRJR_EMPLOYEE
FOR EACH ROW 
BEGIN
	SELECT MAX(EMPLOYEE_ID)+1 INTO :NEW.EMPLOYEE_ID FROM RCJNFRJR_EMPLOYEE;

	IF(:NEW.EMPLOYEE_ID IS NULL)THEN
		:NEW.EMPLOYEE_ID := 1;
	END IF;
END;



CREATE OR REPLACE TRIGGER RCJNFRJR_PK_REGISTER
BEFORE INSERT
ON RCJNFRJR_REGISTER
FOR EACH ROW 
BEGIN
	SELECT MAX(ID_REGISTER)+1 INTO :NEW.ID_REGISTER FROM RCJNFRJR_EMPLOYEE;

	IF(:NEW.ID_REGISTER IS NULL)THEN
		:NEW.ID_REGISTER := 1;
	END IF;
END;